### ISSUE TITLE
Do we want this repository to be public?

### ISSUE THREAD

**Issue by tomchor** [Ocean-Dynamics-Group/GroupExpectations#3]
At the moment this repository is public, which means that anyone can see the files, issue and PRs here. I understand this was probably done in the first place so that the group website can directly link to the PDF generated in this repository, which makes things much easier from a practical standpoint. 

However, it does mean that anyone that finds this repo can get a glimpse into some inner-workings of the group, all the discussions we have here, etc. I'm creating this just so that we're aware of this, and to confirm that that's really the behavior we want! If not, @wenegrat can always change the repo settings later.

cc: @igoruchoa @rwegener2 @reint-fischer @whitleyv @sjlama (did I forget anyone? I couldn't find George's github handle)

**Comment by wenegrat** [comment]
The expectations document itself is publicly available (and in fact one of the first things I encourage anyone who is interested in joining the group to read!). So I guess my inclination is that it would likewise be fine for discussions leading in to editing it to also remain public. However, if others have concerns about this (for instance if it might stifle discussion in some way), we can _definitiely_ change! 

(George never got me a github ID, maybe ask him about it when you meet this week).

**Comment by tomchor** [comment]
> The expectations document itself is publicly available (and in fact one of the first things I encourage anyone who is interested in joining the group to read!). So I guess my inclination is that it would likewise be fine for discussions leading in to editing it to also remain public.

Agreed!

**Comment by tomchor** [comment]
Since no one else voiced an opinion and we're in agreement, should we close this issue?
